### ISSUE TITLE
Version updation simplified

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-homepage#9]
Earlier I had made version updation a part of the cronjob.
As mentioned by @funderburkjim , it would be difficult to sell the automation idea to him urgently.
Therefore, I am dropping that idea for now.
For version updation on csl-homepage, a small script has been prepared.
https://github.com/sanskrit-lexicon/csl-homepage/blob/master/update_version.sh

It would be much easier and easily acceptable alternative to Jim.

# Explanation about the code
```bash
echo "STEP 1. UPDATE THE .VERSION FILE."
cd ../csl-orig
echo "2.0.`git log | grep '^commit' | wc -l`" > .version
```
The machine goes to the csl-orig repository and calculates the commits made in that repository. If the commits made hitherto are 569, it stores the version `2.0.569` in the csl-orig/.version file.

```bash
echo "STEP 2. UPDATE COLOGNE HOMEPAGE TO DISPLAY TODAY'S DATE."
cd ../csl-homepage
bash redo_xampp.sh
```
Update the local display to show the version number stored in csl-orig/.version file.

**Comment by drdhaval2785** [comment]
I think, now the code should be much more suitable for usage, @funderburkjim .
Kindly give it a try and let me know.

Only presumption is that csl-orig and csl-homepage are siblings.
This holds true in both Cologne and Xampp installations, as far as I know. 

If you run `redo_cologne.sh` instead of `redo_xampp.sh` in the above script, Cologne server version should get updated in the same way.

**Comment by funderburkjim** [comment]
## .version for dummies
There is a lot packed into 
```
echo "2.0.`git log | grep '^commit' | wc -l`" > .version
```


Here is a *for dummies* explanation.

### git log
This is a normal part of git command line.  If issued in any repository, it presents an interactive display.
For instance, in csl-orig on local system it shows in the terminal:
```
commit e6646b55de3c471bbb28284edfffb7eee55547f7 (HEAD -> master, origin/master, origin/HEAD)
Author: Dhaval Patel <drdhaval2785@gmail.com>
Date:   Mon Sep 13 15:14:53 2021 +0530

    close #623

commit 66ab72df8de5a143fd196e727018069d20aacf7d
Author: Dhaval Patel <drdhaval2785@gmail.com>
Date:   Mon Sep 13 14:00:16 2021 +0530

    preserve period in https://github.com/sanskrit-lexicon/csl-devanagari/issues/16 part 2

commit 3b48cb11bef98df699dc51743de873af8f63a167
:
```
and waits at the ':' prompt at bottom for either `q` (to quit) or `<space bar>`  to show next screen-ful of commits.
The top line is the latest commit.

## pipe into grep
`git log | grep '^commit'`

This is not interactive, but functionally does two things:
1.  The entire log file is printed to some output stream (stdout probably)
2. The separate unix 'grep' command is applied to this output
   * in our case, the lines of output that start with 'commit' are selected

The result is printed to terminal output:
```
jimfu@DESKTOP-6PTUC6R MINGW64 /c/xampp/htdocs/cologne/csl-orig (master)
$ git log | grep '^commit'
commit e6646b55de3c471bbb28284edfffb7eee55547f7
commit 66ab72df8de5a143fd196e727018069d20aacf7d
commit 3b48cb11bef98df699dc51743de873af8f63a167
AND MANY MORE LINES, 1 for each commit to the csl-orig repository
```

## wc -l
Next, pipe the previous listing of commits thru the `wc` unix command, and use
the '-l'  (ell) option of 'wc' (word count)  to count the number of lines, and send that number to the output
```
jimfu@DESKTOP-6PTUC6R MINGW64 /c/xampp/htdocs/cologne/csl-orig (master)
$ git log | grep '^commit' | wc -l
600
```
So we now know, at the moment, that there are 600 commits to csl-orig.

## construct a string with the number of commits
```
echo "2.0.`git log | grep '^commit' | wc -l`" 
```
The backticks before `git` and after `wc-l`    indicate the previous command is to be run, and the output 
is to be returned (rather than sent to stdout)
After interpolation of the '600'  we get the double quoted string becomes  `2.0.600`.
The 'echo' command just sends this string to stdout again.  
```
jimfu@DESKTOP-6PTUC6R MINGW64 /c/xampp/htdocs/cologne/csl-orig (master)
$ echo "2.0.`git log | grep '^commit' | wc -l`"
2.0.600
```

## putting the string into .version file
Instead of sending the version string to stdout, we redirect stdout to a file, in this case the .version file
```
jimfu@DESKTOP-6PTUC6R MINGW64 /c/xampp/htdocs/cologne/csl-orig (master)
echo "2.0.`git log | grep '^commit' | wc -l`" > .version
```
we can now do other things with this .version file.
For experiment, we can just 'cat' it to see what is there.
```
jimfu@DESKTOP-6PTUC6R MINGW64 /c/xampp/htdocs/cologne/csl-orig (master)
$ cat .version
2.0.600
```

## .version is not tracked by git
This is because .version is in the .gitignore file for csl-orig
```
jimfu@DESKTOP-6PTUC6R MINGW64 /c/xampp/htdocs/cologne/csl-orig (master)
$ cat .gitignore
v00/csl-data/APScan/*
v00/csl-data/PDScan/*
v02/pd/*
v02/ap/*
temp*
*~
v02/.xampp_last_run
v02/.files_to_handle
v02/.cologne_last_run
.version
```

@drdhaval2785  has his reasons for this and has described those reasons somewhere.

Thus endeth the *for dummies* digression; we know now that the version is 
2.0.N,  where N is the number of commits in the csl-orig repository.

**Comment by funderburkjim** [comment]
## modify update_version.sh

Remove 'redo_xampp.sh' from script.  
```
git diff update_version.sh
 echo "2.0.`git log | grep '^commit' | wc -l`" > .version

-echo "STEP 2. UPDATE COLOGNE HOMEPAGE TO DISPLAY TODAY'S DATE."
 cd ../csl-homepage
-bash redo_xampp.sh
+echo "STEP 2: RERUN REDO_XAMPP.SH OR REDO_COLOGNE.SH, AS APPROPRIATE"
```
Reason:  We need to do update_version.sh both in xampp installation and in cologne installation.

Alternatively, could have altered redo_xampp.sh and redo_cologne.sh to put 'sh update_version.sh' in each.

**Comment by funderburkjim** [comment]
## the procedure for redo

```
sh update_version.sh  
sh redo_xampp.sh  # for xampp installation
   OR
sh redo_cologne.sh # for cologne server
```

**Comment by funderburkjim** [comment]
@drdhaval2785 

I like the update_version.sh script.
Have used it both on local installation and cologne server, without a hitch.

Feel safely back in my security blankets :)

I think this issue may be closed.

**Comment by drdhaval2785** [comment]
# Reason for not tracking .version file

As mentioned above, the version is 2.0.N where N is the number of commits in csl-orig.
If I track .version file via csl-orig, I would have to do either of two
1. Manually update .version file before committing any change
2. After making change to a file, I commit that change; and then make another commit to update the version number. 

I found both the solution suboptimal, because it puts additional burden to the user.
And generating .version file via git log hack shown above is very easy, and reproducible.
So, decided to keep it outside git tracking.

**Comment by drdhaval2785** [comment]
Great to see the version number seen on https://www.sanskrit-lexicon.uni-koeln.de/ .

**Comment by funderburkjim** [comment]
## Change to version 2.4.0
Revise script [update_version.sh](https://github.com/sanskrit-lexicon/csl-homepage/blob/master/update_version.sh).

Whenever we redo the home page  (e.g. `sh redo_xampp.sh` or `sh redo_cologne.sh`),
we can first run `sh update_version.sh`.

The current major-minor part of the semantic version is set to '2.4'.
The major part '2' is consistent with the 'v0' in csl-orig/v02, csl-pywork/v02, and csl-websanlexicon/v02.
The minor part '4' is **the number of dictionaries added after the base collection**.
Currently, there are 4 such dictionaries:  LAN, ARMH, PWKVN, and LRV.

The patch part is computed as 'ncommit - patchbase', where
* ncommit is current number of commits in csl-orig
* patchbase is the number of commits in csl-orig WHEN MAJORMINOR changed last.

majorminor and patchbase are hardcoded in update_version.sh.
When another change is made to majorminor, we need to manually revise
`majorminor` and `patchbase` in update_version.sh.
To get the new value of patchbase,
```
cd csl-orig
git log | grep '^commit' | wc -l
```

The 'version' at homepage (cologne or local) now shows as 2.4.0.

**Comment by funderburkjim** [comment]
@drdhaval2785 Does the above look ok?  
Do you confirm my choice of '4' for minor part?

**Comment by gasyoun** [comment]
> Do you confirm my choice of '4' for minor part?

Seems semantic enough ))

**Comment by drdhaval2785** [comment]
I agree
